import { Expense, MonthlyBudget, ShoppingList, UserProfile } from '../types';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'u1',
    name: 'Alex (You)',
    initials: 'AL',
    avatarColor: '#059669',
    email: 'alex@example.com',
    isCurrentUser: true,
  },
  {
    id: 'u2',
    name: 'Elena',
    initials: 'EL',
    avatarColor: '#8B5CF6',
    email: 'elena@example.com',
    isCurrentUser: false,
  },
  {
    id: 'u3',
    name: 'Marco',
    initials: 'MA',
    avatarColor: '#F59E0B',
    email: 'marco@example.com',
    isCurrentUser: false,
  },
];

export const INITIAL_BUDGET: MonthlyBudget = {
  month: '2026-09',
  totalLimit: 2400,
  categoryLimits: {
    'Groceries': 600,
    'Dining & Takeout': 250,
    'Utilities & Bills': 200,
    'Transportation': 150,
    'Rent & Housing': 950,
    'Entertainment & Leisure': 150,
    'Healthcare': 100,
  },
};

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-1',
    title: 'Lidl Supermarket',
    amount: 46.80,
    category: 'Groceries',
    date: '2026-09-21T14:30:00.000Z',
    paymentMethod: 'Debit Card',
    paidByUserId: 'u1',
    notes: 'Weekly fresh produce & essentials',
  },
  {
    id: 'exp-2',
    title: 'Metro / Transit Monthly Pass',
    amount: 35.00,
    category: 'Transportation',
    date: '2026-09-20T08:15:00.000Z',
    paymentMethod: 'Apple Pay / Google Pay',
    paidByUserId: 'u1',
  },
  {
    id: 'exp-3',
    title: 'Electricity & Gas Bill',
    amount: 85.20,
    category: 'Utilities & Bills',
    date: '2026-09-18T10:00:00.000Z',
    paymentMethod: 'Bank Transfer / SEPA',
    paidByUserId: 'u1',
  },
  {
    id: 'exp-4',
    title: 'Trattoria Bella Notte',
    amount: 38.00,
    category: 'Dining & Takeout',
    date: '2026-09-16T20:45:00.000Z',
    paymentMethod: 'Credit Card',
    paidByUserId: 'u1',
    notes: 'Dinner with Elena & Marco',
  },
  {
    id: 'exp-5',
    title: 'City Pharmacy',
    amount: 18.50,
    category: 'Healthcare',
    date: '2026-09-14T11:20:00.000Z',
    paymentMethod: 'Cash',
    paidByUserId: 'u1',
  },
  {
    id: 'exp-6',
    title: 'Apartment Rent Contribution',
    amount: 950.00,
    category: 'Rent & Housing',
    date: '2026-09-01T09:00:00.000Z',
    paymentMethod: 'Bank Transfer / SEPA',
    paidByUserId: 'u1',
  },
  {
    id: 'exp-7',
    title: 'Movie Tickets & Snacks',
    amount: 24.50,
    category: 'Entertainment & Leisure',
    date: '2026-09-10T19:30:00.000Z',
    paymentMethod: 'Apple Pay / Google Pay',
    paidByUserId: 'u1',
  },
];

export const INITIAL_SHOPPING_LISTS: ShoppingList[] = [
  {
    id: 'list-1',
    name: 'Weekly Lidl Grocery Run',
    storeName: 'Lidl',
    color: '#0050AA',
    shareCode: 'LIDL-4821',
    collaboratorIds: ['u1', 'u2', 'u3'],
    isArchived: false,
    createdAt: '2026-09-21T09:00:00.000Z',
    items: [
      {
        id: 'item-101',
        name: 'Organic Whole Milk',
        quantity: '2L',
        estimatedPrice: 2.98,
        aisle: 'Dairy & Eggs',
        isCompleted: true,
        addedByUserId: 'u1',
        assignedToUserId: 'u1',
      },
      {
        id: 'item-102',
        name: 'Free-Range Eggs (6pk)',
        quantity: '1 pack',
        estimatedPrice: 2.39,
        aisle: 'Dairy & Eggs',
        isCompleted: true,
        addedByUserId: 'u2',
        assignedToUserId: 'u2',
      },
      {
        id: 'item-103',
        name: 'Fresh Bananas',
        quantity: '1 kg',
        estimatedPrice: 1.65,
        aisle: 'Fresh Produce',
        isCompleted: true,
        addedByUserId: 'u1',
      },
      {
        id: 'item-104',
        name: 'Sourdough Bread',
        quantity: '1 loaf',
        estimatedPrice: 2.20,
        aisle: 'Bakery',
        isCompleted: false,
        addedByUserId: 'u3',
        assignedToUserId: 'u3',
      },
      {
        id: 'item-105',
        name: 'Extra Virgin Olive Oil',
        quantity: '1 bottle (750ml)',
        estimatedPrice: 6.99,
        aisle: 'Pantry & Dry Goods',
        isCompleted: false,
        addedByUserId: 'u1',
      },
      {
        id: 'item-106',
        name: 'Chicken Breast Fillets',
        quantity: '500g',
        estimatedPrice: 6.40,
        aisle: 'Meat & Fish',
        isCompleted: false,
        addedByUserId: 'u2',
        assignedToUserId: 'u1',
      },
      {
        id: 'item-107',
        name: 'Greek Yogurt 500g',
        quantity: '2 tubs',
        estimatedPrice: 3.78,
        aisle: 'Dairy & Eggs',
        isCompleted: false,
        addedByUserId: 'u1',
      },
    ],
  },
  {
    id: 'list-2',
    name: 'Weekend Dinner Party',
    storeName: 'Carrefour',
    color: '#004F9F',
    shareCode: 'CAR-9102',
    collaboratorIds: ['u1', 'u2'],
    isArchived: false,
    createdAt: '2026-09-20T17:00:00.000Z',
    items: [
      {
        id: 'item-201',
        name: 'Italian Pasta (Spaghetti)',
        quantity: '1 kg',
        estimatedPrice: 2.30,
        aisle: 'Pantry & Dry Goods',
        isCompleted: true,
        addedByUserId: 'u1',
      },
      {
        id: 'item-202',
        name: 'Pecorino Romano Cheese',
        quantity: '250g',
        estimatedPrice: 4.80,
        aisle: 'Dairy & Eggs',
        isCompleted: false,
        addedByUserId: 'u1',
      },
      {
        id: 'item-203',
        name: 'Guanciale / Bacon',
        quantity: '300g',
        estimatedPrice: 5.50,
        aisle: 'Meat & Fish',
        isCompleted: false,
        addedByUserId: 'u2',
        assignedToUserId: 'u2',
      },
      {
        id: 'item-204',
        name: 'San Marzano Canned Tomatoes',
        quantity: '2 cans',
        estimatedPrice: 3.20,
        aisle: 'Pantry & Dry Goods',
        isCompleted: false,
        addedByUserId: 'u1',
      },
    ],
  },
  {
    id: 'list-3',
    name: 'Home Essentials',
    storeName: 'Supermarket / General',
    color: '#059669',
    shareCode: 'HOME-1029',
    collaboratorIds: ['u1', 'u3'],
    isArchived: false,
    createdAt: '2026-09-18T11:00:00.000Z',
    items: [
      {
        id: 'item-301',
        name: 'Eco Dish Soap',
        quantity: '1 bottle',
        estimatedPrice: 1.85,
        aisle: 'Household & Cleaning',
        isCompleted: true,
        addedByUserId: 'u3',
      },
      {
        id: 'item-302',
        name: 'Recycled Paper Towels',
        quantity: '4 rolls',
        estimatedPrice: 3.49,
        aisle: 'Household & Cleaning',
        isCompleted: false,
        addedByUserId: 'u1',
      },
    ],
  },
];
