export const THEME = {
  colors: {
    primary: '#059669', // Emerald Green
    primaryLight: '#D1FAE5',
    primaryDark: '#065F46',
    accent: '#4F46E5', // Indigo
    accentLight: '#EEF2FF',
    accentDark: '#3730A3',
    background: '#F8FAFC',
    surface: '#FFFFFF',
    surfaceSubtle: '#F1F5F9',
    surfaceBorder: '#E2E8F0',
    textPrimary: '#0F172A',
    textSecondary: '#64748B',
    textMuted: '#94A3B8',
    textInverse: '#FFFFFF',
    danger: '#EF4444',
    dangerLight: '#FEE2E2',
    warning: '#F59E0B',
    warningLight: '#FEF3C7',
    success: '#10B981',
    successLight: '#ECFDF5',
    info: '#3B82F6',
    infoLight: '#EFF6FF',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
  },
  borderRadius: {
    sm: 6,
    md: 10,
    lg: 14,
    xl: 20,
    full: 9999,
  },
  typography: {
    titleLarge: { fontSize: 26, fontWeight: '700' as const, lineHeight: 32 },
    titleMedium: { fontSize: 20, fontWeight: '700' as const, lineHeight: 26 },
    titleSmall: { fontSize: 16, fontWeight: '600' as const, lineHeight: 22 },
    body: { fontSize: 14, fontWeight: '400' as const, lineHeight: 20 },
    bodyMedium: { fontSize: 14, fontWeight: '500' as const, lineHeight: 20 },
    bodyBold: { fontSize: 14, fontWeight: '700' as const, lineHeight: 20 },
    caption: { fontSize: 12, fontWeight: '400' as const, lineHeight: 16 },
    captionBold: { fontSize: 12, fontWeight: '600' as const, lineHeight: 16 },
  },
  shadows: {
    card: {
      shadowColor: '#0F172A',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    floating: {
      shadowColor: '#059669',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 10,
      elevation: 6,
    },
  },
};
